<?php
include_once("CE.php");
include_once("CQ.php");
include_once("CWE.php");
include_once("CX.php");
include_once("ED.php");
include_once("EI.php");
include_once("EIP.php");
include_once("FN.php");
include_once("HD.php");
include_once("MSG.php");
include_once("PL.php");
include_once("PRL.php");
include_once("PT.php");
include_once("RP.php");
include_once("SAD.php");
include_once("SN.php");
include_once("TS.php");
include_once("VID.php");
include_once("XAD.php");
include_once("XCN.php");
include_once("XON.php");
include_once("XPN.php");
?>
